sudo: required
services:
  - docker
  
before_install:
  - docker build -t mituverma/docker-react -f Dockerfile.dev .
  
script:
  - docker run mituverma/docker-react npm run test -- --coverage
  
deploy:
  provider: elasticbeanstalk
  region:"us-east-2"
  app: "docker-react"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-444395533317"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  